@startuml

skinparam linetype ortho
skinparam rectangle {
  BackgroundColor White
  BorderColor Black
}

' Contexte
package "Informations contextuelles" {
  class FRCorePatient [[https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-patient]]
  class FRCoreOrganization [[https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-organization]]
  class FRCoreEncounter [[https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-encounter]]
  class FRCorePractitioner [[https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-practitioner]]
  class "Observation (*)" as Observation
}

package "Médicament prescrit" {
  class FRMedicationNonCompound [[./StructureDefinition-fr-medication-noncompound.html]]
  class FRMedicationCompound [[./StructureDefinition-fr-medication-compound.html]]
}

class "FRMedicationRequest" [[./StructureDefinition-fr-medicationrequest.html]]
class "FRInpatientMedicationRequest" [[./StructureDefinition-fr-inpatient-medicationrequest.html]]


' Notes pour les ValueSets
note right of FRMedicationRequest
  ValueSet:
  - FRRouteOfAdministration
  - FRMethodOfAdministration
end note

note right of FRMedicationNonCompound
  ValueSet:
  - FRMedicationCode
  - MpSubstanceActive
  - FRMpDoseForm
end note

note right of FRMedicationCompound
  ValueSet:
  - FRMpDoseForm
end note

' Relations principales
FRMedicationRequest --> "Informations contextuelles"

FRMedicationRequest --> "Médicament prescrit"

FRMedicationNonCompound --> FRMedicationCompound

@enduml
